"""
Max Pain calculator for Deribit options (BTC / ETH / SOL / HYPE).

Fetches open interest for all options from Deribit's public API,
groups by expiry, and computes the Max Pain strike per expiry.
BTC/ETH are inverse options; SOL/HYPE are USDC-settled (linear),
where OI is normalized by contract size so totals are in coins.

Usage:
    python maxpain.py                              # print all expiries (BTC)
    python maxpain.py --currency SOL               # same for SOL (or ETH / HYPE)
    python maxpain.py --top 6                      # top 6 expiries by total OI
    python maxpain.py --top 8 --pine out.pine      # also generate a TradingView Pine Script
"""

import argparse
import json
import re
import urllib.request
from collections import defaultdict
from datetime import datetime, timezone

BOOK_API = "https://www.deribit.com/api/v2/public/get_book_summary_by_currency?currency={cur}&kind=option"
INSTRUMENTS_API = "https://www.deribit.com/api/v2/public/get_instruments?currency={cur}&kind=option"

# display currency -> (Deribit API currency, instrument-name prefix)
# BTC/ETH are inverse options; the rest live under the USDC linear group.
MARKETS = {
    "BTC": ("BTC", "BTC"),
    "ETH": ("ETH", "ETH"),
    "SOL": ("USDC", "SOL_USDC"),
    "HYPE": ("USDC", "HYPE_USDC"),
}


def instrument_re(prefix):
    # e.g. BTC-26SEP26-120000-C, SOL_USDC-28AUG26-116-C, XRP_USDC-25SEP26-1d35-C
    # ('d' is Deribit's decimal point in fractional strikes)
    return re.compile(rf"^{prefix}-(\d{{1,2}}[A-Z]{{3}}\d{{2}})-(\d+(?:d\d+)?)-([CP])$")


def parse_strike(s):
    return float(s.replace("d", "."))


def _get(url):
    req = urllib.request.Request(url, headers={"User-Agent": "maxpain-script"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return json.load(resp)["result"]


def fetch_book(api_currency):
    return _get(BOOK_API.format(cur=api_currency))


def fetch_contract_sizes(api_currency):
    """instrument_name -> contract size (coins per contract). 1.0 for inverse options."""
    return {d["instrument_name"]: float(d.get("contract_size") or 1.0)
            for d in _get(INSTRUMENTS_API.format(cur=api_currency))}


def parse_expiry(s):
    return datetime.strptime(s, "%d%b%y").replace(hour=8, tzinfo=timezone.utc)  # Deribit settles 08:00 UTC


def max_pain(options, candidates=None):
    """options: list of (strike, type, oi). Returns (max_pain_strike, payout_at_mp).

    candidates: strikes to evaluate; defaults to the strikes present in options.
    Passing every listed strike of the chain (incl. zero-OI ones) matches the
    common convention -- on ties the lowest strike wins.
    """
    strikes = sorted(candidates if candidates else {o[0] for o in options})
    best_strike, best_payout = None, float("inf")
    for s in strikes:
        payout = 0.0
        for strike, typ, oi in options:
            if typ == "C" and s > strike:
                payout += oi * (s - strike)
            elif typ == "P" and s < strike:
                payout += oi * (strike - s)
        if payout < best_payout:
            best_strike, best_payout = s, payout
    return best_strike, best_payout


PINE_TEMPLATE = """\
//@version=6
indicator("{cur} Max Pain (Deribit)", "Max Pain", overlay = true, max_lines_count = 100, max_labels_count = 100)

// Generated by maxpain.py on {generated_at}  (underlying ~ ${underlying:,.0f})
// Each line = Max Pain of one expiry, drawn from the last bar to its settlement time (08:00 UTC).
// Each expiry gets its own color; the label sits at the LEFT end of the line.
// Line width scales with total OI of that expiry.
//
// DAILY UPDATE -- no code edits needed:
//   run:  python maxpain.py --currency {cur} --top 8 --clip
//   then: indicator Settings > paste (Ctrl+V) into the "Data" field.
//
// Note: on intraday timeframes TradingView clamps drawings ~500 bars into the future,
// so far expiries may appear closer than they are -- use the D or W timeframe for the full picture.

dataStr     = input.text_area("{datastr}", "Data (YYMMDD:maxpain:oi, comma-separated)")
showOI      = input.bool(true, "Show total OI in label")
hideExpired = input.bool(true, "Hide expired")

var string[] monthNames = array.from("JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC")
var color[]  palette    = array.from(color.orange, color.aqua, color.lime, color.fuchsia, color.yellow, color.red, color.teal, color.purple)

var line[]  lns = array.new<line>()
var label[] lbs = array.new<label>()

if barstate.islast
    for l in lns
        line.delete(l)
    for lb in lbs
        label.delete(lb)
    array.clear(lns)
    array.clear(lbs)
    items = str.split(dataStr, ",")
    float maxOi = 0.0
    for it in items
        p = str.split(str.trim(it), ":")
        if array.size(p) == 3
            maxOi := math.max(maxOi, nz(str.tonumber(array.get(p, 2))))
    float[] usedPx = array.new<float>()
    int drawn = 0
    for it in items
        p = str.split(str.trim(it), ":")
        if array.size(p) == 3
            d  = int(nz(str.tonumber(array.get(p, 0))))
            px = nz(str.tonumber(array.get(p, 1)))
            oi = nz(str.tonumber(array.get(p, 2)))
            yy = d / 10000
            mm = d / 100 % 100
            dd = d % 100
            expT = timestamp("UTC", 2000 + yy, mm, dd, 8, 0)
            if not hideExpired or expT > time
                col = array.get(palette, drawn % array.size(palette))
                drawn += 1
                w = oi >= 0.5 * maxOi ? 3 : oi >= 0.15 * maxOi ? 2 : 1
                array.push(lns, line.new(time, px, expT, px, xloc = xloc.bar_time, color = col, style = line.style_dashed, width = w))
                // labels sit at the LEFT end of each line; when several expiries share the same
                // max pain price, each duplicate is nudged further left so labels don't overlap
                dup = 0
                for u in usedPx
                    if u == px
                        dup += 1
                array.push(usedPx, px)
                lx = time - dup * 30 * timeframe.in_seconds() * 1000
                expName = (dd < 10 ? "0" : "") + str.tostring(dd) + array.get(monthNames, mm - 1) + str.tostring(yy)
                txt = expName + "  " + str.tostring(px, "#.####")
                if showOI
                    txt := txt + "  |  OI " + str.tostring(oi, "#") + " {cur}"
                array.push(lbs, label.new(lx, px, txt, xloc = xloc.bar_time, style = label.style_label_right, color = color.new(col, 85), textcolor = col, size = size.small))
"""


def data_string(rows):
    """Compact data string for the indicator's Data input: YYMMDD:maxpain:oi,..."""
    return ",".join(f"{r[0]:%y%m%d}:{r[2]:g}:{r[3]:.0f}" for r in rows)


def copy_to_clipboard(text):
    import subprocess
    subprocess.run("clip", input=text.encode("ascii"), check=True)


def generate_pine(rows, underlying_price, out_path, currency):
    """rows: sorted list of (dt, expiry, mp, total_oi, n)."""
    pine = PINE_TEMPLATE.format(
        generated_at=f"{datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC}",
        underlying=underlying_price,
        datastr=data_string(rows),
        cur=currency,
    )
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(pine)
    print(f"\nPine Script written to: {out_path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--currency", default="BTC", choices=list(MARKETS), help="Deribit currency (default: BTC)")
    ap.add_argument("--top", type=int, default=0, help="show only top N expiries by total OI")
    ap.add_argument("--pine", metavar="FILE", help="write a TradingView Pine Script to FILE")
    ap.add_argument("--string", action="store_true", help="print the compact data string for the indicator's Data input")
    ap.add_argument("--clip", action="store_true", help="copy the data string to the clipboard")
    args = ap.parse_args()

    cur = args.currency
    api_cur, prefix = MARKETS[cur]
    book = fetch_book(api_cur)
    sizes = fetch_contract_sizes(api_cur)
    rx = instrument_re(prefix)
    by_expiry = defaultdict(list)
    chain_strikes = defaultdict(set)  # all listed strikes per expiry, incl. zero-OI
    underlying_price = None

    for item in book:
        name = item["instrument_name"]
        m = rx.match(name)
        if not m:
            continue
        expiry, strike, typ = m.group(1), parse_strike(m.group(2)), m.group(3)
        chain_strikes[expiry].add(strike)
        oi = (item.get("open_interest") or 0.0) * sizes.get(name, 1.0)
        if oi > 0:
            by_expiry[expiry].append((strike, typ, oi))
        if underlying_price is None and item.get("underlying_price"):
            underlying_price = item["underlying_price"]

    rows = []
    for expiry, options in by_expiry.items():
        mp, _ = max_pain(options, chain_strikes[expiry])
        total_oi = sum(o[2] for o in options)
        rows.append((parse_expiry(expiry), expiry, mp, total_oi, len(options)))
    rows.sort(key=lambda r: r[0])

    if args.top:
        keep = set(sorted(rows, key=lambda r: -r[3])[: args.top])
        rows = [r for r in rows if r in keep]

    print(f"\nDeribit {cur} options -- underlying ~ ${underlying_price:,.0f}"
          f"  ({datetime.now(timezone.utc):%Y-%m-%d %H:%M UTC})\n")
    print(f"{'Expiry':<10} {'Max Pain':>10} {f'Total OI ({cur})':>15} {'Contracts':>10}")
    print("-" * 50)
    for dt, expiry, mp, total_oi, n in rows:
        print(f"{expiry:<10} {mp:>10,.10g} {total_oi:>15,.0f} {n:>10}")

    if args.pine:
        generate_pine(rows, underlying_price, args.pine, cur)

    if args.string or args.clip:
        s = data_string(rows)
        print(f"\nData string:\n{s}")
        if args.clip:
            copy_to_clipboard(s)
            print("(copied to clipboard -- paste into the indicator's Data field)")


if __name__ == "__main__":
    main()
